# Generated by Django 3.1.7 on 2022-02-10 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assemblee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.TextField(blank=True, null=True)),
                ('situation', models.TextField(blank=True, null=True)),
                ('num_ville', models.TextField(blank=True, null=True)),
                ('num_dirigeant', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'assemblee',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cantique',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.TextField(blank=True, null=True)),
                ('titre', models.TextField(blank=True, null=True)),
                ('lien_audio', models.TextField(blank=True, null=True)),
                ('file_name', models.TextField(blank=True, null=True)),
                ('num_chantre', models.TextField(blank=True, null=True)),
                ('duration', models.IntegerField(blank=True, null=True)),
                ('paroles', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'cantique',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Chantre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.TextField(blank=True, null=True)),
                ('nom', models.TextField(blank=True, null=True)),
                ('position', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'chantre',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Charge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.TextField(blank=True, null=True)),
                ('titre', models.TextField(blank=True, null=True)),
                ('id_langue', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'charge',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Concordance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_pred', models.TextField(blank=True, null=True)),
                ('num_verset', models.TextField(blank=True, null=True)),
                ('concordance', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'concordance',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Confirmes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.TextField(blank=True, null=True)),
                ('nom', models.TextField(blank=True, null=True)),
                ('detail', models.TextField(blank=True, null=True)),
                ('ref_image', models.TextField(blank=True, null=True)),
                ('sigle_pays', models.TextField(blank=True, null=True)),
                ('lien', models.TextField(blank=True, null=True)),
                ('lien_image', models.TextField(blank=True, null=True)),
                ('page_facebook', models.TextField(blank=True, null=True)),
                ('page_youtube', models.TextField(blank=True, null=True)),
                ('id_langue', models.IntegerField()),
            ],
            options={
                'db_table': 'confirmes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Dirigeant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.TextField(blank=True, null=True)),
                ('nom', models.TextField(blank=True, null=True)),
                ('tel1', models.TextField(blank=True, null=True)),
                ('tel2', models.TextField(blank=True, null=True)),
                ('email', models.TextField(blank=True, null=True)),
                ('page_facebook', models.TextField(blank=True, null=True)),
                ('page_youtube', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'dirigeant',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Langue',
            fields=[
                ('_id', models.AutoField(primary_key=True, serialize=False)),
                ('initial', models.TextField()),
                ('nom_langue', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'langue',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Livre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lien_pdf', models.TextField(blank=True, null=True)),
                ('nom_livre', models.TextField(blank=True, null=True)),
                ('extrait_de', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'livre',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ministre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.TextField(blank=True, null=True)),
                ('nom', models.TextField(blank=True, null=True)),
                ('tel1', models.TextField(blank=True, null=True)),
                ('tel2', models.TextField(blank=True, null=True)),
                ('email', models.TextField(blank=True, null=True)),
                ('num_charge', models.TextField(blank=True, null=True)),
                ('sigle_pays', models.TextField(blank=True, null=True)),
                ('page_facebook', models.TextField(blank=True, null=True)),
                ('page_youtube', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ministre',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pays',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.TextField(blank=True, null=True)),
                ('sigle', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'pays',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True)),
                ('lien', models.TextField(blank=True, null=True)),
                ('id_langue', models.IntegerField()),
            ],
            options={
                'db_table': 'photo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Predication',
            fields=[
                ('_id', models.AutoField(primary_key=True, serialize=False)),
                ('numero', models.TextField(blank=True, null=True)),
                ('chapitre', models.TextField(blank=True, null=True)),
                ('titre', models.TextField()),
                ('sous_titre', models.TextField(blank=True, null=True)),
                ('nom_audio', models.TextField(blank=True, null=True)),
                ('lien_audio', models.TextField(blank=True, null=True)),
                ('duree', models.IntegerField(blank=True, null=True)),
                ('lien_video', models.TextField(blank=True, null=True)),
                ('similar_sermon', models.TextField(blank=True, null=True)),
                ('lien_pdf', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'predication',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Temoignage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.TextField(blank=True, null=True)),
                ('texte', models.TextField(blank=True, null=True)),
                ('id_langue', models.IntegerField()),
            ],
            options={
                'db_table': 'temoignage',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Verset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.TextField(blank=True, null=True)),
                ('contenu', models.TextField(blank=True, null=True)),
                ('info', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'verset',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('lien', models.TextField(blank=True, null=True)),
                ('type', models.TextField(blank=True, null=True)),
                ('id_langue', models.IntegerField()),
            ],
            options={
                'db_table': 'video',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ville',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.TextField(blank=True, null=True)),
                ('nom', models.TextField(blank=True, null=True)),
                ('sigle_pays', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ville',
                'managed': False,
            },
        ),
    ]
