# Generated by Django 3.0 on 2021-02-27 10:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Langue',
            fields=[
                ('field_id', models.AutoField(db_column='_id', primary_key=True, serialize=False)),
                ('initial', models.TextField()),
                ('classe', models.TextField(blank=True, null=True)),
                ('type_contenu', models.TextField(blank=True, null=True)),
                ('sens_lecture', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'langue',
            },
        ),
        migrations.CreateModel(
            name='Predication',
            fields=[
                ('field_id', models.AutoField(db_column='', primary_key=True, serialize=False)),
                ('numero', models.IntegerField(blank=True, null=True)),
                ('nom_pred', models.TextField(blank=True, null=True)),
                ('titre', models.TextField(blank=True, null=True)),
                ('sous_titre', models.TextField(blank=True, null=True)),
                ('nom_audio', models.TextField(blank=True, null=True)),
                ('lien_audio', models.TextField(blank=True, null=True)),
                ('duree', models.IntegerField(blank=True, null=True)),
                ('lien_video', models.TextField(blank=True, null=True)),
                ('id_langue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Langue')),
            ],
            options={
                'db_table': 'predication',
            },
        ),
        migrations.CreateModel(
            name='Verset',
            fields=[
                ('field_id', models.AutoField(db_column='', primary_key=True, serialize=False)),
                ('numero', models.IntegerField(blank=True, null=True)),
                ('contenu', models.TextField(blank=True, null=True)),
                ('id_langue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Langue')),
                ('id_pred', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Predication')),
            ],
            options={
                'db_table': 'verset',
            },
        ),
    ]
